# Generated by Django 5.2.1 on 2025-07-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('smiles', models.TextField(blank=True, null=True)),
                ('standard', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('chinese_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latin_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tissue', models.CharField(blank=True, max_length=255, null=True)),
                ('precursor_mz', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('ionmode', models.CharField(blank=True, max_length=255, null=True)),
                ('rtinseconds', models.FloatField(blank=True, null=True)),
                ('pepmass', models.CharField(blank=True, max_length=255, null=True)),
                ('spectrum_type', models.CharField(choices=[('sample', 'sample'), ('standard', 'standard')], default='sample', max_length=16)),
                ('spectrum_blob', models.BinaryField(blank=True, null=True)),
                ('peaks', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'spectrum_type'], name='web_compoun_title_d83a9b_idx')],
            },
        ),
    ]
