# Generated by Django 5.2 on 2026-06-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('matched_spectrum_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('smiles', models.TextField(blank=True, null=True)),
                ('inchikey', models.CharField(blank=True, db_index=True, max_length=27, null=True)),
                ('morgan_fp', models.BinaryField(blank=True, null=True)),
                ('standard', models.TextField(blank=True, null=True)),
                ('chinese_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latin_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tissue', models.CharField(blank=True, max_length=255, null=True)),
                ('precursor_mz', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('ionmode', models.CharField(blank=True, max_length=255, null=True)),
                ('rtinseconds', models.FloatField(blank=True, null=True)),
                ('pepmass', models.CharField(blank=True, max_length=255, null=True)),
                ('mw', models.FloatField(blank=True, db_index=True, null=True)),
                ('antitumor', models.BooleanField(db_index=True, default=False, help_text='Whether the compound is antitumor')),
                ('spectrum_type', models.CharField(choices=[('sample', 'sample'), ('standard', 'standard')], default='sample', max_length=16)),
                ('spectrum_blob', models.BinaryField(blank=True, null=True)),
                ('peaks', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
