# Generated by Django 5.2.1 on 2025-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_compoundlibrary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
