# Generated by Django 5.2.1 on 2025-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_compoundlibrary_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='compoundlibrary',
            name='web_compoun_title_d83a9b_idx',
        ),
        migrations.AlterField(
            model_name='compoundlibrary',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True),
        ),
        migrations.AddIndex(
            model_name='compoundlibrary',
            index=models.Index(fields=['spectrum_type'], name='web_compoun_spectru_0f0085_idx'),
        ),
    ]
