# Generated by Django 5.2.1 on 2025-07-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_compoundlibrary_web_compoun_title_d83a9b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='title',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
