# Generated by Django 5.2.1 on 2025-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_compoundlibrary_web_compoun_spectru_0f0085_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='compoundlibrary',
            index=models.Index(fields=['spectrum_type'], name='web_compoun_spectru_0f0085_idx'),
        ),
    ]
