# Generated by Django 5.2.1 on 2025-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_compoundlibrary_web_compoun_spectru_0f0085_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
