# Generated by Django 5.2.1 on 2025-08-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_compoundlibrary_web_compoun_title_9e94e2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('latin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chinese_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tissue', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        # migrations.RemoveIndex(
        #     model_name='compoundlibrary',
        #     name='web_compoun_title_9e94e2_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='compoundlibrary',
        #     name='web_compoun_spectru_0f0085_idx',
        # ),
        migrations.AddField(
            model_name='compoundsimilarity',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_compounds', to='web.compoundlibrary'),
        ),
        migrations.AddField(
            model_name='compoundsimilarity',
            name='similar_compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_similar_to', to='web.compoundlibrary'),
        ),
        migrations.AddIndex(
            model_name='compoundsimilarity',
            index=models.Index(fields=['compound'], name='web_compoun_compoun_5885e3_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundsimilarity',
            index=models.Index(fields=['similar_compound'], name='web_compoun_similar_dadc1c_idx'),
        ),
    ]
