# Generated by Django 5.2.1 on 2025-08-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_compoundsimilarity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compoundsimilarity',
            options={'verbose_name': 'Compound Similarity', 'verbose_name_plural': 'Compound Similarities'},
        ),
        # migrations.RemoveIndex(
        #     model_name='compoundlibrary',
        #     name='web_compoun_title_9e94e2_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='compoundlibrary',
        #     name='web_compoun_spectru_0f0085_idx',
        # ),
    ]
