# Generated by Django 5.2.1 on 2025-08-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_compoundsimilarity_options_and_more'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='compoundlibrary',
        #     name='web_compoun_title_9e94e2_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='compoundlibrary',
        #     name='web_compoun_spectru_0f0085_idx',
        # ),
    ]
