# Generated by Django 5.2.1 on 2025-08-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_compoundlibrary_web_compoun_title_9e94e2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoundsimilarity',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='compoundsimilarity',
            name='similar_compound',
        ),
        migrations.RemoveIndex(
            model_name='compoundlibrary',
            name='web_compoun_title_9e94e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='compoundlibrary',
            name='web_compoun_spectru_0f0085_idx',
        ),
        migrations.DeleteModel(
            name='CompoundSimilarity',
        ),
    ]
