# Generated by Django 5.2.1 on 2025-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_compoundsimilarity_compound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundlibrary',
            name='spectrum_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
