# Generated by Django 5.2.1 on 2025-09-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_compoundlibrary_spectrum_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundlibrary',
            name='matched_spectrum_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
