# Generated by Django 5.2.1 on 2025-10-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_compoundlibrary_matched_spectrum_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundStaticTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(max_length=50)),
                ('html_content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.compoundlibrary')),
            ],
            options={
                'unique_together': {('compound', 'table_type')},
            },
        ),
    ]
