# Generated by Django 5.2.1 on 2025-10-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_compoundstatictable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompoundStaticTable',
        ),
    ]
