# Generated by Django 5.2.1 on 2025-10-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_delete_compoundstatictable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='standard',
            field=models.TextField(blank=True, null=True),
        ),
    ]
