# Generated by Django 5.2.1 on 2025-10-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_compoundlibrary_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoundlibrary',
            old_name='spectrum_id',
            new_name='STANDARD_ID',
        ),
    ]
