# Generated by Django 5.2.1 on 2025-10-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_rename_spectrum_id_compoundlibrary_standard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundlibrary',
            name='PLANTS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
