# Generated by Django 5.2.1 on 2025-10-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_compoundlibrary_plants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoundlibrary',
            old_name='PLANTS',
            new_name='plants',
        ),
        migrations.RenameField(
            model_name='compoundlibrary',
            old_name='STANDARD_ID',
            new_name='standard_id',
        ),
    ]
