# Generated by Django 5.2 on 2025-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_rename_plants_compoundlibrary_plants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundlibrary',
            name='morgan_fp',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
