# Generated by Django 5.2 on 2025-12-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_compoundlibrary_morgan_fp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='plants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
