# Generated by Django 5.2 on 2025-12-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_compoundlibrary_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='plants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
