# Generated by Django 5.2 on 2026-01-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_compoundlibrary_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='plants',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
