# Generated by Django 5.2 on 2026-01-13 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_compoundlibrary_plants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50, unique=True)),
                ('chinese_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=200)),
                ('tissue', models.CharField(max_length=100)),
                ('precursor_mz', models.FloatField()),
                ('ionmode', models.CharField(max_length=20)),
                ('spectrum_blob', models.BinaryField(blank=True, null=True)),
                ('peaks', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundPlantMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('precursor_mz', models.FloatField()),
                ('ionmode', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_matches', to='web.compoundlibrary')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_matches', to='web.plantspectrum')),
            ],
            options={
                'indexes': [models.Index(fields=['compound', 'score'], name='web_compoun_compoun_4c62fd_idx')],
                'unique_together': {('compound', 'plant')},
            },
        ),
    ]
