# Generated by Django 5.2 on 2026-01-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_plantspectrum_compoundplantmatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompoundPlantMatch',
        ),
        migrations.DeleteModel(
            name='PlantSpectrum',
        ),
    ]
