# Generated by Django 5.2 on 2026-01-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_delete_compoundplantmatch_delete_plantspectrum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='plants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
