# Generated by Django 5.2 on 2026-01-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_compoundlibrary_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundlibrary',
            name='inchikey',
            field=models.CharField(blank=True, db_index=True, max_length=27, null=True),
        ),
    ]
